# Generated by Django 3.2.7 on 2021-10-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='start',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('starts', models.DateField()),
                ('finish', models.DateField()),
                ('remote', models.BooleanField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.technology')),
            ],
        ),
    ]
